# 1. Сюда приходят все, кто ввёл http://. Мы их принудительно перекидываем на https://
server {
    listen 80;
    server_name food.mpnw.online; # ЗАМЕНИ НА СВОЙ ДОМЕН

    return 301 https://$host$request_uri;
}

# 2. Основной безопасный сервер HTTPS
server {
    listen 443 ssl;
    server_name food.mpnw.online; # ЗАМЕНИ НА СВОЙ ДОМЕН

    # Пути к сертификатам внутри контейнера (Nginx возьмет их отсюда)
    ssl_certificate /etc/letsencrypt/live/food.mpnw.online/fullchain.pem; # ЗАМЕНИ site.com в пути
    ssl_certificate_key /etc/letsencrypt/live/food.mpnw.online/privkey.pem; # ЗАМЕНИ site.com в пути

    # Настройки безопасности SSL (современный стандарт)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Раздача фронтенда (HTML, CSS, JS)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Перенаправление запросов к API
    location /api/ {
        proxy_pass http://mpfood-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded-for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}